import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { getSession } from 'next-auth/react'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/router'
import Link from 'next/link'

const Home: NextPage = () => {
   const [isLoading, setIsLoading] = useState(true)
   const router = useRouter()
   useEffect(() => {
      getSession().then((session) => {
         if (!session) {
            router.replace('/auth')
         } else {
            setIsLoading(false)
         }
      })
   }, [router])

   if (isLoading) {
      return <p>Loading...</p>
   }
   return (
      <div className="container flex flex-col justify-center items-center h-screen">
         <Head>
            <title>Welcome to Epic Road Trip</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <h1 className="text-3xl font-bold text-slate-900 text-center mb-5">
            Welcome To Epic Road Trip !
         </h1>
         <div className="w-6/12 flex justify-center">
            <Link href={`/places/`}>
               <a
                  className="
                        rounded 
                        bg-emerald-500 
                        flex-1 
                        text-slate-50 
                        font-bold
                        mx-5 
                        py-2 
                        text-center 
                        hover:bg-emerald-400 
                        transition-all 
                        hover:scale-110
                        hover:translate-y-1
                    "
                    >
                        Create an itinerary
                    </a>
                </Link>
                <Link href={`/map`}>
                    <a
                        className="
                        rounded 
                        border-2 
                        border-emerald-500 
                        flex-1 
                        font-bold 
                        text-emerald-500 
                        mx-5 
                        py-2 
                        text-center 
                        transition-all 
                        hover:scale-110
                        hover:translate-y-1
                    "
               >
                  Visualize an itinerary
               </a>
            </Link>
         </div>
      </div>
   )
}

export default Home
